"""Generate docs/API_REFERENCE.md from the app's OpenAPI schema.

Run from BE/:  python -m scripts.export_api_docs
(the app only needs its normal settings/.env to import; no database connection is made)
"""

import sys
from pathlib import Path

from app.main import app

OUTPUT = Path(__file__).resolve().parents[2] / "docs" / "API_REFERENCE.md"
_METHODS = ("get", "post", "put", "patch", "delete")


def _schema_name(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if schema.get("type") == "array":
        return f"list[{_schema_name(schema.get('items', {}))}]"
    if "anyOf" in schema:
        return " | ".join(_schema_name(item) for item in schema["anyOf"])
    return schema.get("format") or schema.get("type") or "object"


def _fields(spec: dict, schema: dict) -> list[str]:
    if "$ref" in schema:
        schema = spec["components"]["schemas"][schema["$ref"].rsplit("/", 1)[-1]]
    required = set(schema.get("required", []))
    lines = []
    for name, prop in schema.get("properties", {}).items():
        mark = "" if name in required else "?"
        lines.append(f"`{name}{mark}`: {_schema_name(prop)}")
    return lines


def render() -> str:
    spec = app.openapi()
    by_tag: dict[str, list[tuple[str, str, dict]]] = {}
    for path, item in spec["paths"].items():
        for method in _METHODS:
            if method in item:
                op = item[method]
                by_tag.setdefault(op["tags"][0], []).append((method.upper(), path, op))

    out = [
        f"# {spec['info']['title']} — API reference",
        "",
        "> Generated by `python -m scripts.export_api_docs` from the OpenAPI schema; "
        "do not edit by hand. Live docs: `/docs` (Swagger UI) and `/openapi.json` "
        "(disabled in production).",
        "",
        spec["info"]["description"].strip(),
        "",
        "Field marks: `name?` = optional.",
        "",
    ]
    for tag in spec.get("tags", []):
        rows = by_tag.get(tag["name"])
        if not rows:
            continue
        out += [f"## {tag['name']}", "", tag["description"], ""]
        for method, path, op in rows:
            out += [f"### `{method} {path}` — {op['summary']}", "", op["description"], ""]
            params = [p for p in op.get("parameters", []) if p["in"] in ("path", "query", "header")]
            if params:
                out.append("Parameters: " + ", ".join(
                    f"`{p['name']}` ({p['in']}{', required' if p.get('required') else ''})"
                    for p in params
                ))
                out.append("")
            body = op.get("requestBody", {}).get("content", {}).get("application/json")
            if body:
                out.append("Request body: " + "; ".join(_fields(spec, body["schema"])))
                out.append("")
            statuses = []
            for code, response in op["responses"].items():
                if code == "422":
                    continue
                content = response.get("content", {})
                media = next(iter(content), None)
                target = _schema_name(content[media].get("schema", {})) if media else ""
                statuses.append(f"`{code}`" + (f" {target}" if target else ""))
            out.append("Responses: " + ", ".join(statuses))
            ok = next((r for c, r in op["responses"].items() if c.startswith("2")), {})
            ok_schema = ok.get("content", {}).get("application/json", {}).get("schema")
            if ok_schema:
                fields = _fields(spec, ok_schema)
                if fields:
                    out.append("")
                    out.append("Response fields: " + "; ".join(fields))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(render(), encoding="utf-8")
    sys.stdout.buffer.write(f"wrote {OUTPUT}\n".encode())
